### ISSUE TITLE
Section headings/folding

### ISSUE THREAD

**Issue by jonocarroll** [ThinkRstat/littleboxes#6]
Bonjour! J'aime vraiment ce paquet, mais ça ne va pas bien avec la fonctionnalité de schéma de RStudio.

I notice that the box outlines are identified by RStudio as headings, so I have lots of `(Untitled)` sections in my outline. This is related to #3 where I note extra `###` were added to a line to allow code folding.

The reason for both is that RStudio treats any line ending with 4 or more trailing `-`, `=`, or `#` as a section, see https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections

Might I suggest the following structure for boxes:

```
## ######################################################## ##
#                                                            #
####                       boxed heading                  ####
#                                                            #
## ######################################################## ##
```

for which:

 - the box outline itself is *not* treated as an untitled section (because it does not end in `####`
 - the heading text *is* treated as an appropriately named section
 - the folding works as expected (folds the section) and leaves the title at the top
 - the styling is nicely symmetric and clean.

These need not be spaces - any character that breaks the rule of 4 will do

```
##%########################################################%##
#                                                            #
####                       boxed heading                  ####
#                                                            #
##%########################################################%##
```

Or alternatively, add a secondary short section title in the box

```
# infinite sum #############################################
#                                                          #
#          calculate an infinite sum of a series           #
#                                                          #
#########################################################%##
```

which causes the folding to begin with the top line of the box, but the short title remains visible (and is the name of the section). I have used a single `%` on the bottom of the box to prevent this from becoming a section.

**Comment by VincentGuyader** [comment]
Hi @jonocarroll do you try the modification ? is it ok ?

Regards

**Comment by jonocarroll** [comment]
Looks great, works great! Cheers! Sorry, I Tweeted about it but never did respond here.

https://twitter.com/carroll_jono/status/879482129385574401
